import { Provider, ProviderError } from '@vocaliq/shared';

/**
 * Messenger (Meta) Calling — the ONLY place Messenger Graph-API / calling specifics live (golden rule
 * #2). WebRTC voice calls between a Facebook **Page** and a Messenger **user (PSID)**: signaling for
 * user-initiated (inbound) + Page-initiated (outbound) calls over the Graph API, plus the call-permissions
 * read and call settings. The Page is addressed as `me` with the Page access token (same token Day-93
 * Messenger messaging already uses). HTTP is injected so the adapter is unit-testable offline; the WebRTC
 * MEDIA lives in the voice service, not here. The adapter NEVER bills (cost is metered by the caller,
 * golden rule #4) and never logs the token or SDP.
 *
 * ⚠️ WIRE FORMAT (CLAUDE.md §15). Meta's Messenger Calling API is the architectural sibling of WhatsApp
 * Business Calling (Graph API + WebRTC/OPUS + HMAC webhooks), and the request shapes below are mapped
 * from that documented sibling. The Messenger-specific endpoint paths / field names are NOT fully public
 * and are marked `[CONFIRM @ MEC-00]`; confirming them changes ONLY this file (that is the whole point of
 * keeping it behind the provider seam). Every live path stays gated until MEC-00 proves the format.
 * See `docs/MESSENGER-CALLING-AI-ENGINE-PLAN.md` §A.
 */

/** Graph API version used for Messenger Calling. Overridable per deployment. */
export const MESSENGER_GRAPH_VERSION = 'v21.0';

/** A minimal fetch-like port so the adapter runs with a fake transport in tests. */
export type MeHttp = (
  url: string,
  init: { method: string; headers: Record<string, string>; body?: string },
) => Promise<{ ok: boolean; status: number; text(): Promise<string> }>;

const defaultHttp: MeHttp = (url, init) =>
  fetch(url, { ...init, signal: AbortSignal.timeout(15_000) });

/** The Graph error `code` attached to a thrown {@link ProviderError}, when present. */
export function messengerErrorCode(err: unknown): number | undefined {
  return typeof err === 'object' && err !== null
    ? (err as { meErrorCode?: number }).meErrorCode
    : undefined;
}

export interface MeSession {
  sdpType: 'offer' | 'answer';
  sdp: string;
}

export interface MePlaceCallInput {
  /** Recipient Messenger user PSID (Page-Scoped ID). */
  recipient: string;
  /** The Page's SDP OFFER (generated by the voice-service WebRTC bridge). */
  sdpOffer: string;
  /** Opaque tracking string echoed back on the terminate event. [CONFIRM @ MEC-00: field name.] */
  callbackData?: string;
}

export type MePermissionStatus = 'no_permission' | 'temporary' | 'permanent';

export interface MePermissionActionLimit {
  timePeriod: string;
  maxAllowed: number;
  currentUsage: number;
  limitExpirationTime?: number;
}
export interface MePermissionAction {
  actionName: string;
  canPerformAction: boolean;
  limits: MePermissionActionLimit[];
}
export interface MeCallPermission {
  status: MePermissionStatus;
  expirationTime?: number;
  actions: MePermissionAction[];
}

export class MessengerCallingTelephony {
  readonly provider = Provider.MESSENGER;
  readonly capability = 'telephony' as const;

  /** @param pageAccessToken Page access token (MESSENGER_PAGE_ACCESS_TOKEN). The Page node is `me`. */
  constructor(
    private readonly pageAccessToken: string,
    private readonly opts: { graphVersion?: string; http?: MeHttp } = {},
  ) {}

  private get base(): string {
    return `https://graph.facebook.com/${this.opts.graphVersion ?? MESSENGER_GRAPH_VERSION}`;
  }
  private get http(): MeHttp {
    return this.opts.http ?? defaultHttp;
  }

  /** Bearer-authenticated Graph request. Throws a {@link ProviderError} (with `meErrorCode`) on !ok.
   *  Never includes the token or the request body (SDP) in the thrown message. */
  private async graph(
    method: string,
    path: string,
    body?: unknown,
  ): Promise<Record<string, unknown>> {
    let res: { ok: boolean; status: number; text(): Promise<string> };
    try {
      res = await this.http(`${this.base}${path}`, {
        method,
        headers: {
          Authorization: `Bearer ${this.pageAccessToken}`,
          'Content-Type': 'application/json',
        },
        ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
      });
    } catch (cause) {
      throw new ProviderError('Messenger Graph request failed', { cause });
    }
    const text = await res.text().catch(() => '');
    if (!res.ok) {
      let meErrorCode: number | undefined;
      try {
        meErrorCode = (JSON.parse(text) as { error?: { code?: number } }).error?.code;
      } catch {
        /* non-JSON error body */
      }
      const err = new ProviderError(`Messenger ${method} ${path} error ${res.status}`, {
        // Include only the Graph error code, never the request body (SDP) or token.
        cause: new Error(meErrorCode ? `graph error code ${meErrorCode}` : 'graph error'),
      });
      if (meErrorCode !== undefined) {
        (err as { meErrorCode?: number }).meErrorCode = meErrorCode;
      }
      throw err;
    }
    if (res.status === 204 || text === '') return {};
    try {
      return JSON.parse(text) as Record<string, unknown>;
    } catch {
      return {};
    }
  }

  // ── Signaling: POST /me/calls [CONFIRM @ MEC-00] ────────────────────────────

  /** Page-initiated (outbound) — place a call with the Page SDP offer. Returns Meta's call id. */
  async placeCall(input: MePlaceCallInput): Promise<{ callId: string }> {
    const json = await this.graph('POST', '/me/calls', {
      messaging_product: 'messenger',
      recipient: { id: input.recipient },
      action: 'connect',
      session: { sdp_type: 'offer', sdp: input.sdpOffer },
      ...(input.callbackData ? { biz_opaque_callback_data: input.callbackData } : {}),
    });
    const id =
      (json.calls as Array<{ id?: string }> | undefined)?.[0]?.id ??
      (typeof json.call_id === 'string' ? json.call_id : undefined);
    if (!id) throw new ProviderError('Messenger placeCall did not return a call id');
    return { callId: id };
  }

  /** Inbound — establish the WebRTC media connection early with the SDP answer (recommended). */
  async preAccept(input: { callId: string; sdpAnswer: string }): Promise<void> {
    await this.callAction(input.callId, 'pre_accept', {
      session: { sdp_type: 'answer', sdp: input.sdpAnswer },
    });
  }

  /** Inbound — accept the call with the SDP answer. Flow media only AFTER this resolves. */
  async accept(input: { callId: string; sdpAnswer: string; callbackData?: string }): Promise<void> {
    await this.callAction(input.callId, 'accept', {
      session: { sdp_type: 'answer', sdp: input.sdpAnswer },
      ...(input.callbackData ? { biz_opaque_callback_data: input.callbackData } : {}),
    });
  }

  async reject(callId: string): Promise<void> {
    await this.callAction(callId, 'reject');
  }

  /** Terminate — call this even on RTCP BYE, for accurate billing. */
  async terminate(callId: string): Promise<void> {
    await this.callAction(callId, 'terminate');
  }

  private async callAction(
    callId: string,
    action: 'pre_accept' | 'accept' | 'reject' | 'terminate',
    extra: Record<string, unknown> = {},
  ): Promise<void> {
    await this.graph('POST', '/me/calls', {
      messaging_product: 'messenger',
      call_id: callId,
      action,
      ...extra,
    });
  }

  // ── Permissions: /me/call_permissions [CONFIRM @ MEC-00] ─────────────────────

  /** Current call-permission status + action limits for a user PSID (the outbound gate, MEC-08). */
  async getCallPermission(input: { psid: string }): Promise<MeCallPermission> {
    const q = `recipient=${encodeURIComponent(input.psid)}`;
    const json = await this.graph('GET', `/me/call_permissions?${q}`);
    const perm = (json.permission ?? {}) as {
      status?: MePermissionStatus;
      expiration_time?: number;
    };
    const actions = ((json.actions ?? []) as Array<Record<string, unknown>>).map((a) => ({
      actionName: String(a.action_name ?? ''),
      canPerformAction: Boolean(a.can_perform_action),
      limits: ((a.limits ?? []) as Array<Record<string, unknown>>).map((l) => ({
        timePeriod: String(l.time_period ?? ''),
        maxAllowed: Number(l.max_allowed ?? 0),
        currentUsage: Number(l.current_usage ?? 0),
        ...(l.limit_expiration_time !== undefined
          ? { limitExpirationTime: Number(l.limit_expiration_time) }
          : {}),
      })),
    }));
    return {
      status: perm.status ?? 'no_permission',
      ...(perm.expiration_time !== undefined ? { expirationTime: perm.expiration_time } : {}),
      actions,
    };
  }

  // ── Call settings: /me/settings [CONFIRM @ MEC-00] ──────────────────────────

  async getSettings(): Promise<Record<string, unknown>> {
    return this.graph('GET', '/me/settings');
  }

  /** Update the `calling` settings block (availability / call-button visibility). */
  async updateSettings(calling: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.graph('POST', '/me/settings', { calling });
  }
}
