import { Provider, ProviderError } from '@vocaliq/shared';

/**
 * WhatsApp (Meta) Business Calling — the ONLY place Graph-API / calling specifics live (golden rule
 * #2). Signaling for user-initiated (inbound) + business-initiated (outbound) voice calls over the
 * Cloud API: SDP offer/answer via `POST /<PNID>/calls` (connect/pre_accept/accept/reject/terminate),
 * call permissions via `/messages` + `/call_permissions`, and call settings via `/settings`. HTTP is
 * injected so the adapter is unit-testable offline; the WebRTC MEDIA lives in the voice service, not
 * here. The adapter NEVER bills (cost is metered by the caller, golden rule #4) and never logs the
 * token or SDP. See `docs/WHATSAPP-CALLING-AI-ENGINE-PLAN.md` §A.3–A.6.
 */

/** Graph API version that supports Business Calling. Overridable per deployment. */
export const WHATSAPP_GRAPH_VERSION = 'v21.0';

/** Meta error code returned when the business lacks permission to call a user (§A.4). */
export const WHATSAPP_NO_PERMISSION_CODE = 138006;

/** A minimal fetch-like port so the adapter runs with a fake transport in tests. */
export type WaHttp = (
  url: string,
  init: { method: string; headers: Record<string, string>; body?: string },
) => Promise<{ ok: boolean; status: number; text(): Promise<string> }>;

const defaultHttp: WaHttp = (url, init) =>
  fetch(url, { ...init, signal: AbortSignal.timeout(15_000) });

/** The Graph error `code` attached to a thrown {@link ProviderError}, when present. */
export function whatsappErrorCode(err: unknown): number | undefined {
  return typeof err === 'object' && err !== null
    ? (err as { waErrorCode?: number }).waErrorCode
    : undefined;
}

export interface WaSession {
  sdpType: 'offer' | 'answer';
  sdp: string;
}

export interface WaPlaceCallInput {
  /** Recipient WhatsApp phone number (required unless `recipient` BSUID given). */
  to?: string;
  /** Business-scoped user id (alternative to `to`). */
  recipient?: string;
  /** The business's SDP OFFER (generated by the voice-service WebRTC bridge). */
  sdpOffer: string;
  /** Opaque tracking string (≤512 chars) echoed back in the terminate webhook. */
  callbackData?: string;
}

export type WaPermissionStatus = 'no_permission' | 'temporary' | 'permanent';

export interface WaPermissionActionLimit {
  timePeriod: string;
  maxAllowed: number;
  currentUsage: number;
  limitExpirationTime?: number;
}
export interface WaPermissionAction {
  actionName: string;
  canPerformAction: boolean;
  limits: WaPermissionActionLimit[];
}
export interface WaCallPermission {
  status: WaPermissionStatus;
  expirationTime?: number;
  actions: WaPermissionAction[];
}

export class WhatsAppCallingTelephony {
  readonly provider = Provider.WHATSAPP;
  readonly capability = 'telephony' as const;

  constructor(
    private readonly accessToken: string,
    private readonly phoneNumberId: string,
    private readonly opts: { graphVersion?: string; http?: WaHttp } = {},
  ) {}

  private get base(): string {
    return `https://graph.facebook.com/${this.opts.graphVersion ?? WHATSAPP_GRAPH_VERSION}`;
  }
  private get http(): WaHttp {
    return this.opts.http ?? defaultHttp;
  }

  /** Bearer-authenticated Graph request. Throws a {@link ProviderError} (with `waErrorCode`) on !ok.
   *  Never includes the token or the request body (SDP) in the thrown message. */
  private async graph(
    method: string,
    path: string,
    body?: unknown,
  ): Promise<Record<string, unknown>> {
    let res: { ok: boolean; status: number; text(): Promise<string> };
    try {
      res = await this.http(`${this.base}${path}`, {
        method,
        headers: {
          Authorization: `Bearer ${this.accessToken}`,
          'Content-Type': 'application/json',
        },
        ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
      });
    } catch (cause) {
      throw new ProviderError('WhatsApp Graph request failed', { cause });
    }
    const text = await res.text().catch(() => '');
    if (!res.ok) {
      let waErrorCode: number | undefined;
      try {
        waErrorCode = (JSON.parse(text) as { error?: { code?: number } }).error?.code;
      } catch {
        /* non-JSON error body */
      }
      const err = new ProviderError(`WhatsApp ${method} ${path} error ${res.status}`, {
        // Include only the Graph error code/subcode, never the request body (SDP) or token.
        cause: new Error(waErrorCode ? `graph error code ${waErrorCode}` : 'graph error'),
      });
      if (waErrorCode !== undefined) {
        (err as { waErrorCode?: number }).waErrorCode = waErrorCode;
      }
      throw err;
    }
    if (res.status === 204 || text === '') return {};
    try {
      return JSON.parse(text) as Record<string, unknown>;
    } catch {
      return {};
    }
  }

  private target(to?: string, recipient?: string): Record<string, string> {
    if (recipient) return { recipient };
    if (to) return { to };
    throw new ProviderError('WhatsApp call requires a `to` number or a `recipient` BSUID');
  }

  // ── Signaling: POST /<PNID>/calls ──────────────────────────────────────────

  /** Business-initiated (outbound) — place a call with the business SDP offer. Returns the WACID. */
  async placeCall(input: WaPlaceCallInput): Promise<{ waCallId: string }> {
    const json = await this.graph('POST', `/${this.phoneNumberId}/calls`, {
      messaging_product: 'whatsapp',
      ...this.target(input.to, input.recipient),
      action: 'connect',
      session: { sdp_type: 'offer', sdp: input.sdpOffer },
      ...(input.callbackData ? { biz_opaque_callback_data: input.callbackData } : {}),
    });
    const id = (json.calls as Array<{ id?: string }> | undefined)?.[0]?.id;
    if (!id) throw new ProviderError('WhatsApp placeCall did not return a call id');
    return { waCallId: id };
  }

  /** Inbound — establish the WebRTC media connection early (recommended) with the SDP answer. */
  async preAccept(input: { callId: string; sdpAnswer: string }): Promise<void> {
    await this.callAction(input.callId, 'pre_accept', {
      session: { sdp_type: 'answer', sdp: input.sdpAnswer },
    });
  }

  /** Inbound — accept the call with the SDP answer. Flow media only AFTER this resolves (§A.3). */
  async accept(input: { callId: string; sdpAnswer: string; callbackData?: string }): Promise<void> {
    await this.callAction(input.callId, 'accept', {
      session: { sdp_type: 'answer', sdp: input.sdpAnswer },
      ...(input.callbackData ? { biz_opaque_callback_data: input.callbackData } : {}),
    });
  }

  async reject(callId: string): Promise<void> {
    await this.callAction(callId, 'reject');
  }

  /** Terminate — call this even on RTCP BYE, for accurate billing (§A.3). */
  async terminate(callId: string): Promise<void> {
    await this.callAction(callId, 'terminate');
  }

  private async callAction(
    callId: string,
    action: 'pre_accept' | 'accept' | 'reject' | 'terminate',
    extra: Record<string, unknown> = {},
  ): Promise<void> {
    await this.graph('POST', `/${this.phoneNumberId}/calls`, {
      messaging_product: 'whatsapp',
      call_id: callId,
      action,
      ...extra,
    });
  }

  // ── Permissions ────────────────────────────────────────────────────────────

  /** Ask a user for permission to call them — interactive message, or an approved template. */
  async sendCallPermissionRequest(input: {
    to?: string;
    recipient?: string;
    text?: string;
    templateName?: string;
    languageCode?: string;
  }): Promise<void> {
    const body: Record<string, unknown> = {
      messaging_product: 'whatsapp',
      recipient_type: 'individual',
      ...this.target(input.to, input.recipient),
    };
    if (input.templateName) {
      body.type = 'template';
      body.template = {
        name: input.templateName,
        language: { code: input.languageCode ?? 'en' },
      };
    } else {
      body.type = 'interactive';
      body.interactive = {
        type: 'call_permission_request',
        action: { name: 'call_permission_request' },
        ...(input.text ? { body: { text: input.text } } : {}),
      };
    }
    await this.graph('POST', `/${this.phoneNumberId}/messages`, body);
  }

  /** Current call-permission status + action limits for a user (§A.5). */
  async getCallPermission(input: {
    userWaId?: string;
    recipient?: string;
  }): Promise<WaCallPermission> {
    const q = input.recipient
      ? `recipient=${encodeURIComponent(input.recipient)}`
      : `user_wa_id=${encodeURIComponent(input.userWaId ?? '')}`;
    const json = await this.graph('GET', `/${this.phoneNumberId}/call_permissions?${q}`);
    const perm = (json.permission ?? {}) as {
      status?: WaPermissionStatus;
      expiration_time?: number;
    };
    const actions = ((json.actions ?? []) as Array<Record<string, unknown>>).map((a) => ({
      actionName: String(a.action_name ?? ''),
      canPerformAction: Boolean(a.can_perform_action),
      limits: ((a.limits ?? []) as Array<Record<string, unknown>>).map((l) => ({
        timePeriod: String(l.time_period ?? ''),
        maxAllowed: Number(l.max_allowed ?? 0),
        currentUsage: Number(l.current_usage ?? 0),
        ...(l.limit_expiration_time !== undefined
          ? { limitExpirationTime: Number(l.limit_expiration_time) }
          : {}),
      })),
    }));
    return {
      status: perm.status ?? 'no_permission',
      ...(perm.expiration_time !== undefined ? { expirationTime: perm.expiration_time } : {}),
      actions,
    };
  }

  // ── Call settings: /<PNID>/settings ────────────────────────────────────────

  async getSettings(includeSipCredentials = false): Promise<Record<string, unknown>> {
    const q = includeSipCredentials ? '?include_sip_credentials=true' : '';
    return this.graph('GET', `/${this.phoneNumberId}/settings${q}`);
  }

  /** Update the `calling` settings block (hours/icons/callback/codecs/voicemail/sip). */
  async updateSettings(calling: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.graph('POST', `/${this.phoneNumberId}/settings`, { calling });
  }
}
